### ISSUE TITLE
RapidAPI Key exposed

### ISSUE THREAD

**Issue by Salieri24** [yordanov0502/sportsbook_application_backend#1]
https://github.com/yordanov0502/sportsbook_application_backend/blob/936bf4f367e99295a885b579a0bdf3ad699aeedb/src/main/java/com/example/sportsbook_application_backend/config/RestTemplateConfig.java#L18C29-L18C29

Hello, its been a while!
It would be a good idea to not expose your API keys in public repositories. You can move it to an environment variable and import it into the project using the `@Value` annotation.

Best wishes,
Angel

**Comment by yordanov0502** [comment]
Thanks for the good advice! I fixed it. In fact, the API key expired long time ago and is indeed useless. However, I will keep in mind your recommendation for usage and share of API keys for future projects.
